/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRunsRouteImport } from './routes/api/runs'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiRunsRunIdRouteImport } from './routes/api/runs.$runId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRoute = ApiRunsRouteImport.update({
  id: '/api/runs',
  path: '/api/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRunIdRoute = ApiRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => ApiRunsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/events': typeof ApiEventsRoute
  '/api/runs': typeof ApiRunsRouteWithChildren
  '/api/runs/$runId': typeof ApiRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/events': typeof ApiEventsRoute
  '/api/runs': typeof ApiRunsRouteWithChildren
  '/api/runs/$runId': typeof ApiRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/events': typeof ApiEventsRoute
  '/api/runs': typeof ApiRunsRouteWithChildren
  '/api/runs/$runId': typeof ApiRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/dashboard' | '/api/events' | '/api/runs' | '/api/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/api/events' | '/api/runs' | '/api/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/events'
    | '/api/runs'
    | '/api/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiRunsRoute: typeof ApiRunsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs': {
      id: '/api/runs'
      path: '/api/runs'
      fullPath: '/api/runs'
      preLoaderRoute: typeof ApiRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$runId': {
      id: '/api/runs/$runId'
      path: '/$runId'
      fullPath: '/api/runs/$runId'
      preLoaderRoute: typeof ApiRunsRunIdRouteImport
      parentRoute: typeof ApiRunsRoute
    }
  }
}

interface ApiRunsRouteChildren {
  ApiRunsRunIdRoute: typeof ApiRunsRunIdRoute
}

const ApiRunsRouteChildren: ApiRunsRouteChildren = {
  ApiRunsRunIdRoute: ApiRunsRunIdRoute,
}

const ApiRunsRouteWithChildren =
  ApiRunsRoute._addFileChildren(ApiRunsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiRunsRoute: ApiRunsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
