/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDashboardV1RunsRouteImport } from './routes/api.dashboard.v1.runs'
import { Route as ApiDashboardV1EventsRouteImport } from './routes/api.dashboard.v1.events'
import { Route as ApiDashboardV1RunsRunIdRouteImport } from './routes/api.dashboard.v1.runs.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardV1RunsRoute = ApiDashboardV1RunsRouteImport.update({
  id: '/api/dashboard/v1/runs',
  path: '/api/dashboard/v1/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardV1EventsRoute = ApiDashboardV1EventsRouteImport.update({
  id: '/api/dashboard/v1/events',
  path: '/api/dashboard/v1/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardV1RunsRunIdRoute = ApiDashboardV1RunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => ApiDashboardV1RunsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/dashboard/v1/events': typeof ApiDashboardV1EventsRoute
  '/api/dashboard/v1/runs': typeof ApiDashboardV1RunsRouteWithChildren
  '/api/dashboard/v1/runs/$runId': typeof ApiDashboardV1RunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/dashboard/v1/events': typeof ApiDashboardV1EventsRoute
  '/api/dashboard/v1/runs': typeof ApiDashboardV1RunsRouteWithChildren
  '/api/dashboard/v1/runs/$runId': typeof ApiDashboardV1RunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/dashboard/v1/events': typeof ApiDashboardV1EventsRoute
  '/api/dashboard/v1/runs': typeof ApiDashboardV1RunsRouteWithChildren
  '/api/dashboard/v1/runs/$runId': typeof ApiDashboardV1RunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/dashboard/v1/events'
    | '/api/dashboard/v1/runs'
    | '/api/dashboard/v1/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/dashboard/v1/events'
    | '/api/dashboard/v1/runs'
    | '/api/dashboard/v1/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/api/dashboard/v1/events'
    | '/api/dashboard/v1/runs'
    | '/api/dashboard/v1/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDashboardV1EventsRoute: typeof ApiDashboardV1EventsRoute
  ApiDashboardV1RunsRoute: typeof ApiDashboardV1RunsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/v1/runs': {
      id: '/api/dashboard/v1/runs'
      path: '/api/dashboard/v1/runs'
      fullPath: '/api/dashboard/v1/runs'
      preLoaderRoute: typeof ApiDashboardV1RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/v1/events': {
      id: '/api/dashboard/v1/events'
      path: '/api/dashboard/v1/events'
      fullPath: '/api/dashboard/v1/events'
      preLoaderRoute: typeof ApiDashboardV1EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/v1/runs/$runId': {
      id: '/api/dashboard/v1/runs/$runId'
      path: '/$runId'
      fullPath: '/api/dashboard/v1/runs/$runId'
      preLoaderRoute: typeof ApiDashboardV1RunsRunIdRouteImport
      parentRoute: typeof ApiDashboardV1RunsRoute
    }
  }
}

interface ApiDashboardV1RunsRouteChildren {
  ApiDashboardV1RunsRunIdRoute: typeof ApiDashboardV1RunsRunIdRoute
}

const ApiDashboardV1RunsRouteChildren: ApiDashboardV1RunsRouteChildren = {
  ApiDashboardV1RunsRunIdRoute: ApiDashboardV1RunsRunIdRoute,
}

const ApiDashboardV1RunsRouteWithChildren =
  ApiDashboardV1RunsRoute._addFileChildren(ApiDashboardV1RunsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDashboardV1EventsRoute: ApiDashboardV1EventsRoute,
  ApiDashboardV1RunsRoute: ApiDashboardV1RunsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
